/*

 ROOM_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 40
   Tile set      : C:\gbdk\programs\Tile Designer\room.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#include "my_types.h"

#define map_roomBank 0

extern T_U08 metatiles[];
extern T_U08 map_room[];

extern T_U08 area_tiles[];
extern const T_U16 area_tiles_palette[];

/* End of ROOM_MAP.H */
